# Generated by Django 5.2.17 on 2026-09-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Evaluator', 'Evaluator'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
